name: Build Signed Release APKs (Per ABI)

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      # ساخت خروجی تفکیک‌شده برای هر معماری
      - name: Build Split APKs
        run: flutter build apk --release --split-per-abi

      # آپلود جداگانه APK معماری ARM 64-bit (گوشی‌های جدید)
      - name: Upload ARM64 APK
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-v8a-release
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      # آپلود جداگانه APK معماری ARM 32-bit (گوشی‌های قدیمی)
      - name: Upload ARM32 APK
        uses: actions/upload-artifact@v4
        with:
          name: app-armeabi-v7a-release
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      # آپلود جداگانه APK معماری x86_64 (شبیه‌سازها)
      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v4
        with:
          name: app-x86_64-release
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk